### ISSUE TITLE
The prefix is $ but i can't bind the ClickGui, u know how to do it?

### ISSUE THREAD

**Issue by iBrunnooB** [HausemasterIssue/MoneyMod-Plus-3-SRC#2]

**Comment by HausemasterIssue** [comment]
you shouldn't even be running this.

try mashing random buttons, specifically y, r, o, p, rshift, and the arrow keys are the usual clickgui keys. 

if those dont work mash em all! also the command system should tell u the syntax of a command, like if u type "$bind" it should say something like "$bind [module name] [key]", or just try doing "$bind clickgui p" or "$bind gui p"

**Comment by iBrunnooB** [comment]
I ran it on a virtual machine, i see it doesn’t work, the command $bind doesn’t exist XD... Thanks btw
